#!/bin/bash

set -euo pipefail
cd "$(dirname "$0")"

if [ -d "./lib" ]; then
  SVB_BASE="${SVB_BASE:-./lib}"
else
  SVB_BASE="${SVB_BASE:-/usr/local/lib/svb}"
fi

usage () {
  cat <<'EOF'
svb - the Simple Volume Backup tool

Usage:
  svb <command> <arguments...>

Commands:
  create    Back up a set of Docker volumes to an S3 folder
  restore   Restore an S3 folder into a set of Docker volumes
  recent    List the most recent backups to an S3 bucket
  show      List the volumes and files in a specified backup
  help      Display this message

svb is a simple set of wrappers around Docker and AWS CLI commands, designed to
help back up and restore Docker volumes to/from S3.

Notes:
  * AWS CLI credentials must be set up using beforehand using `aws configure`
  * svb will automatically pull the "busybox:latest" image from Docker Hub
    before performing backup or restore operations
EOF

  if [ "$#" -eq 1 ]; then
    echo -e "\nerror: $1"
    exit 1
  fi

  exit 0
}

if [ "$#" -lt 1 ] || [ "$1" = "help" ]; then
  usage
fi

SUB="$1"
shift

[ ! -x "$SVB_BASE/svb-$SUB" ] && usage "Subcommand '$SUB' does not exist"

exec "$SVB_BASE/svb-$SUB" "$@"
